export const SKILL_ICONS: { name: string; label: string }[] = [
  { name: 'skill-icons:html', label: 'HTML' },
  { name: 'skill-icons:css', label: 'CSS' },
  { name: 'skill-icons:sass', label: 'Sass' },
  { name: 'skill-icons:styledcomponents', label: 'Styled Components' },
  { name: 'skill-icons:tailwindcss-light', label: 'Tailwind CSS' },
  { name: 'skill-icons:typescript', label: 'TypeScript' },
  { name: 'skill-icons:javascript-light', label: 'JavaScript (Light)' },
  { name: 'skill-icons:javascript', label: 'JavaScript' },
  { name: 'skill-icons:alpinejs-light', label: 'Alpine.js' },
  { name: 'skill-icons:htmx-light', label: 'HTMX' },
  { name: 'skill-icons:jquery', label: 'jQuery' },
  { name: 'skill-icons:vuejs-light', label: 'Vue.js' },
  { name: 'skill-icons:nuxtjs-light', label: 'Nuxt.js' },
  { name: 'skill-icons:pinia-light', label: 'Pinia' },
  { name: 'skill-icons:illustrator-light', label: 'Adobe Illustrator (Light)' },
  { name: 'skill-icons:github-light', label: 'GitHub' },
  { name: 'skill-icons:react-light', label: 'React' },
  { name: 'skill-icons:nextjs-light', label: 'Next.js' },
  { name: 'skill-icons:d3-light', label: 'D3.js' },
  { name: 'skill-icons:vite-light', label: 'Vite' },
  { name: 'skill-icons:vitest-light', label: 'Vitest' },
  { name: 'skill-icons:cypress-light', label: 'Cypress' },
  { name: 'skill-icons:ruby', label: 'Ruby' },
  { name: 'skill-icons:rails', label: 'Ruby on Rails' },
  { name: 'skill-icons:figma-light', label: 'Figma' },
  { name: 'skill-icons:illustrator', label: 'Adobe Illustrator' },
  { name: 'skill-icons:aws-light', label: 'AWS' },
  { name: 'skill-icons:heroku', label: 'Heroku' },
  { name: 'skill-icons:netlify-light', label: 'Netlify' },
]
